# Generated by Django 2.2.7 on 2019-11-24 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.CharField(db_index=True, max_length=150)),
                ('details', models.TextField()),
                ('owner', models.CharField(max_length=150)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
